name: Sync HSE folder from Repo A to this

on:
  schedule:
    - cron: '35 6 * * *'    # 9:35 AM Yekaterinburg (6:35 AM UTC)
    - cron: '10 8 * * *'     # 11:10 AM Yekaterinburg (8:10 AM UTC)
    - cron: '0 10 * * *'      # 1:00 PM Yekaterinburg (10:00 AM UTC)
    - cron: '10 11 * * *'     # 2:10 PM Yekaterinburg (11:10 AM UTC)
    - cron: '30 13 * * *'     # 4:30 PM Yekaterinburg (1:30 PM UTC)
    - cron: '10 15 * * *'     # 6:10 PM Yekaterinburg (3:10 PM UTC)
    - cron: '0 20 * * *'      # 11:00 PM Yekaterinburg (8:00 PM UTC)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo B
      uses: actions/checkout@v3
      with:
        repository: K0taka/HSE-notes

    - name: Clone Repo A
      run: |
        git clone --depth 1 -n --sparse --filter=blob:none ${{ secrets.P_TOKEN }} repo_a
        cd repo_a
        git sparse-checkout init --cone
        git sparse-checkout set "HSE University"
        git sparse-checkout add Excalidraw
        git sparse-checkout add .obsidian/plugins/
        git sparse-checkout add .obsidian/app.json
        git sparse-checkout add .obsidian/community-plugins.json
        git checkout main
        cd ..

    - name: Copy HSE folder to Repo B
      run: |
        cp -r repo_a/"HSE University"/* .
        rm -rf repo_a

    - name: Commit and Push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add .
          git commit -m "Automated sync of HSE folder"
          git push
        fi
